
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jatin
 */
public class EmployeesV2 extends javax.swing.JFrame {

    /**
     * Creates new form EmployeesV2
     */
    public EmployeesV2() {
        initComponents();
        tableRefresh();
    }

    public void tableRefresh() {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rms", "root", "");
                PreparedStatement ps = con.prepareStatement("SELECT * FROM employees");
                ResultSet rs = ps.executeQuery();
                while(rs.next())   {
                    String empId = rs.getString("empID");
                    String nam = rs.getString("name");
                    String dob = rs.getString("dob");
                    String ph = rs.getString("ph");
                    //String add = rs.getString("address");
                    String des = rs.getString("desig");
                    //int sal = rs.getInt("sal");
                    String s = rs.getString("salary");
                    
                    model.addRow(new Object[] {empId, nam, des, dob, ph, s});
                }
                        
            } catch (SQLException ex) {
                Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 18, 11));
        jLabel2.setText("Employees");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 122, -1));

        jButton2.setBackground(new java.awt.Color(241, 241, 241));
        jButton2.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(35, 18, 11));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 32));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 275, 32));

        jButton1.setBackground(new java.awt.Color(241, 241, 241));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(35, 18, 11));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, 33));

        jTable1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jTable1.setForeground(new java.awt.Color(35, 18, 11));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Name", "Designation", "DOB", "Phone Number", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(241, 241, 241));
        jTable1.setSelectionBackground(new java.awt.Color(255, 179, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 585, 499));

        jTextField2.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(35, 18, 11));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 300, 35));

        jTextField3.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(35, 18, 11));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 300, 35));

        jTextField4.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(35, 18, 11));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 300, 35));

        jTextField5.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(35, 18, 11));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 300, 35));

        jTextField6.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(35, 18, 11));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 300, 99));

        jTextField7.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(35, 18, 11));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 300, 35));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(35, 18, 11));
        jLabel4.setText("Employee ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 110, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(35, 18, 11));
        jLabel5.setText("Name :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 110, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(35, 18, 11));
        jLabel6.setText("DOB :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 110, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(35, 18, 11));
        jLabel7.setText("Phone Number :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 110, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(35, 18, 11));
        jLabel8.setText("Address :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 110, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(35, 18, 11));
        jLabel9.setText("Designation :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 110, -1));

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(35, 18, 11));
        jLabel10.setText("Salary :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 110, -1));

        jDateChooser1.setBackground(new java.awt.Color(241, 241, 241));
        jDateChooser1.setForeground(new java.awt.Color(35, 18, 11));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 300, 35));

        jButton3.setBackground(new java.awt.Color(241, 241, 241));
        jButton3.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(35, 18, 11));
        jButton3.setText("Insert");
        jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 127, 40));

        jButton4.setBackground(new java.awt.Color(241, 241, 241));
        jButton4.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(35, 18, 11));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 130, 40));

        jButton5.setBackground(new java.awt.Color(241, 241, 241));
        jButton5.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(35, 18, 11));
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 540, 129, 40));

        jPanel2.setBackground(new java.awt.Color(255, 179, 0));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Options().setVisible(true);
        this.dispose();//to close the current jframe
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name =  jTextField1.getText();
        
        DefaultTableModel model = (DefaultTableModel)
        jTable1.getModel();
        int rows=model.getRowCount();
        if (rows>0) {
            for (int i=0; i<rows; i++)
            model.removeRow(0);  // To remove all rows from
        }
        
        if(name.isEmpty())  {
            //jTable1.setRowText("");
            JOptionPane.showMessageDialog(this,"Please enter name");
            tableRefresh();
            return;
        }
            
        try {
            // TODO code application logic here
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rms", "root", "");
                PreparedStatement ps = con.prepareStatement("SELECT * FROM employees WHERE name LIKE ?");
                ps.setString(1, "%" + name + "%");
                ResultSet rs = ps.executeQuery();
                
                while(rs.next())   {
                    String empId = rs.getString("empID");
                    String nam = rs.getString("name");
                    String dob = rs.getString("dob");
                    String ph = rs.getString("ph");
                    //String add = rs.getString("address");
                    String des = rs.getString("desig");
                    //int sal = rs.getInt("sal");
                    String s = rs.getString("salary");
                    
                    model.addRow(new Object[] {empId, nam, des, dob, ph, s});
                }
            } catch (SQLException ex) {
                Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String empId = jTextField2.getText();
        String name = jTextField3.getText();
        String dob = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText(); //thanks Indunil
        String phone = jTextField4.getText();
        String add = jTextField6.getText();
        String des = jTextField7.getText();
        String sal = jTextField5.getText();
        if(empId.isEmpty() || name.isEmpty() || dob.isEmpty() || phone.isEmpty() || add.isEmpty() || des.isEmpty() || sal.isEmpty())    {
            JOptionPane.showMessageDialog(this, "Please enter all the fields");
            return;
        }
        String[] s = {empId, name, dob, phone, add, des, sal};
        new InsertPassword(s, this).setVisible(true);
        tableRefresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        if(r >= 0)   {
            jTextField2.setText(jTable1.getValueAt(r,0).toString());
            jTextField3.setText(jTable1.getValueAt(r,1).toString());
            jTextField4.setText(jTable1.getValueAt(r,4).toString());
            jTextField7.setText(jTable1.getValueAt(r,2).toString());
            jTextField5.setText(jTable1.getValueAt(r,5).toString());
            String date = jTable1.getValueAt(r,3).toString();
            java.util.Date date2;
            try {
                date2 = new SimpleDateFormat("yyyy-MM-dd").parse(date);
                jDateChooser1.setDate(date2);
            } catch (ParseException ex) {
                Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
            }

            
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rms", "root", "");
                PreparedStatement ps = con.prepareStatement("SELECT address FROM employees WHERE empID = ?");
                ps.setString(1, jTable1.getValueAt(r,0).toString());
                
                ResultSet rs = ps.executeQuery();
                if(rs.next())   {
                    jTextField6.setText(rs.getString("address"));
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() >= 0) {
            String empId = jTextField2.getText();
            String name = jTextField3.getText();
            String dob = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText(); //thanks Indunil
            String phone = jTextField4.getText();
            String add = jTextField6.getText();
            String des = jTextField7.getText();
            String sal = jTextField5.getText();
            if(empId.isEmpty() || name.isEmpty() || dob.isEmpty() || phone.isEmpty() || add.isEmpty() || des.isEmpty() || sal.isEmpty())    {
                JOptionPane.showMessageDialog(this, "Please enter all the fields");
                return;
            }
            
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                
                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rms", "root", "");
                    PreparedStatement ps = con.prepareStatement("UPDATE employees SET name = ?, dob = ?, ph = ?, address = ?, desig = ?, salary = ? WHERE empID = ?");
                    
                    ps.setString(1, name);
                    ps.setString(2, dob);
                    ps.setString(3, phone);
                    ps.setString(4, add);
                    ps.setString(5, des);
                    ps.setString(6, sal);
                    ps.setString(7, empId);
                    
                    ps.execute();
                    tableRefresh();
                } catch (SQLException ex) {
                    Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else    {
            JOptionPane.showMessageDialog(this, "Please select an Item to be updated");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int s = jTable1.getSelectedRow();
        if(s != -1) {
        int result = JOptionPane.showConfirmDialog(this,"Sure? You want to Delete?", "Swing Tester",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rms", "root", "");
                PreparedStatement ps = con.prepareStatement("DELETE FROM employees WHERE empID = ?");
                String k = jTable1.getValueAt(s, 0).toString();
                ps.setString(1, k);
                ps.execute();
                JOptionPane.showMessageDialog(this, "Selected row deleted successfully");
            } catch (SQLException ex) {
                Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeesV2.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        tableRefresh();
        }
        else    {
               JOptionPane.showMessageDialog(this, "Please select a row");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeesV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeesV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeesV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeesV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeesV2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
